# Form implementation generated from reading ui file 'E:\Studying\KTLT\comprehensive-kiosk-management-app\kiosk_app\views\BankCancelDialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class BankCancelDialog(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("BankCancelDialog")
        self.resize(414, 165)
        self.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dialogIcon = QtWidgets.QLabel(parent=self)
        self.dialogIcon.setText("")
        self.dialogIcon.setObjectName("dialogIcon")
        self.horizontalLayout.addWidget(self.dialogIcon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dialogTitleLabel = QtWidgets.QLabel(parent=self)
        self.dialogTitleLabel.setObjectName("dialogTitleLabel")
        self.verticalLayout_2.addWidget(self.dialogTitleLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 8)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.dialogSubtitleLabel = QtWidgets.QLabel(parent=self)
        self.dialogSubtitleLabel.setWordWrap(True)
        self.dialogSubtitleLabel.setObjectName("dialogSubtitleLabel")
        self.verticalLayout.addWidget(self.dialogSubtitleLabel)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.dialogTitleLabel.setText(_translate("BankCancelDialog", "Bạn muốn huỷ đơn hàng hiện tại?"))
        self.dialogSubtitleLabel.setText(_translate("BankCancelDialog", "Bạn không thể quay lại màn hình trước đó khi đã chọn thanh toán."))
